# Utiliser une image Node.js pour la construction
FROM node:18 AS build

# Créer un répertoire pour l'application
WORKDIR /usr/src/app

# Copier les fichiers package.json et package-lock.json
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier le reste du code source
COPY . .

# Construire l'application React
RUN npm run build

# Utiliser l'image Nginx pour servir les fichiers construits
FROM nginx:alpine

# Copier les fichiers construits depuis l'étape précédente
COPY --from=build /usr/src/app/build /usr/share/nginx/html

# Copier une configuration personnalisée pour Nginx, si nécessaire
COPY nginx.conf /etc/nginx/nginx.conf

# Exposer le port sur lequel Nginx fonctionne
EXPOSE 80

# Démarrer Nginx
CMD ["nginx", "-g", "daemon off;"]
